services:
  pgsql_db:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${CONTAINER_NAME}
    hostname: ${HOSTNAME}
    ports:
      - "5433:5432"
    #restart: always
    environment:
      - POSTGRES_USER=${USER_NAME}
      - POSTGRES_PASSWORD=${USER_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_vol:/var/lib/postgresql/data

volumes:
  db_vol:

